# Run pytest on every push to the repository

name: Unit Tests

on:
  push:
    paths:
      - 'web_server'
      - 'tests'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run tests
        run: |
          pytest tests/
